### ISSUE TITLE
💄 Make it pretty

### ISSUE THREAD

**Issue by Yago** [frontend/toolbox-reader#1]
Still bloody ugly, make it nice
f.ex: https://github.com/alexpate/awesome-design-systems

**Comment by tonifisler** [comment]
Moodboard: https://projects.invisionapp.com/d/main#/projects/boards/5523196

**Comment by Yago** [comment]
As discussed with @guillaumeberry, we will start on the following structure and improve with peering session.

![ultimate_toolbox](https://user-images.githubusercontent.com/2025924/29348936-494bee46-8257-11e7-97ab-ed3d1e72005c.png)

**Comment by Yago** [comment]
And because we have the full view feature, we can have a tighter content column and the related issue: adding the toolbar #12

**Comment by Yago** [comment]
It's much better with #30
