### ISSUE TITLE
Add Toolbar

### ISSUE THREAD

**Issue by Yago** [frontend/toolbox-reader#12]
Able to : 
- Display by default the Toolbox identity and any define brand
- toggle the menu, the search and other future features.

![ultimate_toolbox](https://user-images.githubusercontent.com/2025924/29349931-a1602ed0-825c-11e7-9bff-1a135604b93a.png)

**Comment by tonifisler** [comment]
The toolbar is implemented, we just need to define what to put inside it :)

**Comment by Yago** [comment]
should be better with #30
