### ISSUE TITLE
CSS without B4

### ISSUE THREAD

**Issue by Yago** [frontend/toolbox-reader#15]
Make the styleguide work without (and with) Bootstrap 4.

**Comment by tonifisler** [comment]
Currently testing all my code with and without B4

**Comment by Yago** [comment]
should be better with #30

**Comment by tonifisler** [comment]
⚠️ The default styles are currently overriding a lot of stuff of our projects. It has to be more specific and never alter the wrappers of the examples.

https://github.com/frontend/toolbox-reader/blob/5a4b87fbc20b74fa65f0abf8e163a5a501ebd3e9/src/components/App/App.scss#L9-L11

This is forcing the system fonts in my project. :(
