### ISSUE TITLE
Markdown table rendering not working

### ISSUE THREAD

**Issue by guillaumeberry** [frontend/toolbox-reader#41]
Tried to use the markdown syntax to rendre tables in documentation… And it doesn't work (yet)!

---

**Tested:**
- with and without linebreak before
- with and without <br> before
- with regular markdown syntax (with and without columns alignments)
- with GitHub markdown syntax

---

| Tables        | Are           | Cool  |
| ------------- |:-------------:| -----:|
| col 3 is      | right-aligned | $1600 |
| col 2 is      | centered      |   $12 |
| zebra stripes | are neat      |    $1 |

**Comment by knuch** [comment]
Same here, would love the feature 😁
