### ISSUE TITLE
Limit max width of content

### ISSUE THREAD

**Issue by knuch** [frontend/toolbox-reader#42]
On wide screens, reading some pages is kind of difficult. 
What about adding a `.container` on `.tlbx-content > div` to limit the max width?

before: 
![capture d ecran 2018-08-06 a 11 14 56](https://user-images.githubusercontent.com/4548432/43708138-0d8ee8ce-996a-11e8-91cc-8eb2ee75cf91.png)

after: 
![capture d ecran 2018-08-06 a 11 15 28](https://user-images.githubusercontent.com/4548432/43708145-12720f06-996a-11e8-86df-3573d13ee462.png)

**Comment by tonifisler** [comment]
Quite opinionated, I would suggest doing that from the `styleguide.scss` file in your project.

**Comment by Yago** [comment]
I agreed with @tonifisler and I think [opinionated libraries](https://github.com/prettier/prettier/issues/5948) can be “user unfriendly”
