### ISSUE TITLE
Yellow banner still display after following update procedure

### ISSUE THREAD

**Issue by knuch** [frontend/toolbox-reader#45]
after following http://frontend.github.io/toolbox/updates.html on a fresh project, The banner stilly displays as follows:
![Capture d’écran 2019-05-14 à 14 40 14](https://user-images.githubusercontent.com/4548432/57698612-519cb400-7656-11e9-93e9-d0f77d0ce45f.png)

**Comment by Yago** [comment]
It happens when I create the new bundle before bumping the version in the `package.json` 😅 Should be fixed with the `2.2.2` 🤞
