### ISSUE TITLE
Who's Conor?

### ISSUE THREAD

**Issue by knuch** [frontend/toolbox-reader#46]
Joke aside, I have weird `console.log('Conor')` from my console, that triggers my code debugger. It's quite painful.

hotfix:
- close inspector
- refresh
- disable the code preview with the left bar link
- open inspector
- refresh

![Capture d’écran 2019-05-14 à 14 28 08](https://user-images.githubusercontent.com/4548432/57699131-77768880-7657-11e9-900d-ea50c201f680.png)

![Capture d’écran 2019-05-14 à 14 35 56](https://user-images.githubusercontent.com/4548432/57699146-7ba2a600-7657-11e9-8552-f5521a1e9abb.png)

**Comment by Yago** [comment]
It's Conor Hastings, maintenainer of `conorhastings/react-syntax-highlighter`. Apparently he publish the `10.2.1` on NPM with this nice `console.log` 😅

**Comment by Yago** [comment]
It's @conorhastings, maintainer of [`react-syntax-highlighter`](https://www.npmjs.com/package/react-syntax-highlighter). Apparently there is published versions on NPM with this nice `console.log` 😅 

See : 
- current:  https://cdn.jsdelivr.net/npm/react-syntax-highlighter@10.2.1/dist/highlight.js
- latest: https://cdn.jsdelivr.net/npm/react-syntax-highlighter@10.3.0/dist/highlight.js

[Issue](https://github.com/conorhastings/react-syntax-highlighter/issues/192) open on the repo 😉

**Comment by conorhastings** [comment]
published a patch version removing console.log, so sorry

**Comment by knuch** [comment]
Thanks a lot @conorhastings !

**Comment by Yago** [comment]
@conorhastings No worries, thank you for your work ! 😄
