### ISSUE TITLE
Styleguide styles (config + css)

### ISSUE THREAD

**Issue by WengerK** [frontend/toolbox-reader#6]
Hey mates I faced an issue when I want to override some css only for the styleguide.

My website use `html { font-size: 48px; }` but I want to keep the default size on the Styleguide.
I try to use the `assets/config/styleguide.scss` file with `html { font-size: 16px !important; }` but it seems this file is not used anywhere.

How could I achieve my goal ?

**Comment by Yago** [comment]
We need two things here : 
- some basic configuration (in `toolbox.json` ?)
- a `styleguide.scss` fully working to fix components in the styleguide

**Comment by tonifisler** [comment]
This will mostly impact Toolbox Utils, see https://github.com/frontend/toolbox-utils/issues/14

**Comment by tonifisler** [comment]
Implemented in https://github.com/frontend/toolbox-utils/pull/18
