### ISSUE TITLE
Add custom blocks in index.html

### ISSUE THREAD

**Issue by WengerK** [frontend/toolbox-reader#7]
Hey guys,

Nice job about this amazing Styleguide.

I'm facing an issue, how could I add Typekit to my Styleguide and so use my fonts ?
Also, what about CDN or custom scripts?

**Comment by gido** [comment]
This is issue start to be blocking to run javascript in the styleguide. Eq: antistatique/ovv#15

**Comment by tonifisler** [comment]
Will be doable once https://github.com/frontend/toolbox-utils/pull/18 is merged.
